#!/bin/bash

VERSION=1.4.8
FILE=zstd-$VERSION.tar.gz
DIR=zstd-$VERSION
URL=https://github.com/facebook/zstd/archive/v$VERSION.tar.gz
ORIG_DIR=$(pwd)

function error
{
    >&2 echo "Error: $1"
}

function abort
{
    error "$1"
    exit 1
}

function set_tempdir
{
    fix=$1
    if TMPDIR=$(mktemp -d --suffix=$fix 2>/dev/null); then
        return 0
    fi

    if TMPDIR=$(mktemp -d -t $fix); then
        return 0
    fi

    abort "could not create a temporary directory"
}
set_tempdir zstd

function set_logfile
{
    fix=$1
    if LOGFILE=$(mktemp --suffix=$fix.log 2>/dev/null); then
        return 0
    fi

    if LOGFILE=$(mktemp -t $fix.log); then
        return 0
    fi

    abort "could not create a log file"
}
set_logfile zstd

exec 3> "$LOGFILE"

function cleanup
{
    exec 3>&-
    rm -rf "$TMPDIR" >/dev/null 2>&1 || true
    cd "$ORIG_DIR"
}
trap cleanup EXIT

function silent_run
{
    eval "$@" 2>&3 1>&3
}

function run_ldconfig
{
    if type ldconfig; then
        ldconfig
    fi
}

function failed
{
    exec 3>&-
    echo "FAILED."
    echo
    echo "---------------------------------------- log begin ----------------------------------------"
    cat "$LOGFILE"
    echo "----------------------------------------  log end  ----------------------------------------"
    echo
    echo "LOG: $LOGFILE"
    exit 1
}
trap failed INT

function succeeded
{
    cleanup
    rm -rf "$LOGFILE" >/dev/null 2>&1 || true
}

echo "[0/5] Library(zstd==$VERSION)"
cd $TMPDIR

echo -n "[1/5] Downloading... "
silent_run curl -o $FILE -L $URL
[ $? == 0 ] && echo "done." || failed

echo -n "[2/5] Extracting... "
silent_run tar xzf $FILE && silent_run cd $DIR
[ $? == 0 ] && echo "done." || failed

echo -n "[3/5] Compiling... "
silent_run make
[ $? == 0 ] && echo "done." || failed

echo -n "[4/5] Installing... "
make install
[ $? == 0 ] && echo "done." || failed

echo -n "[5/5] Finalizing... "
silent_run run_ldconfig
[ $? == 0 ] && echo "done." || failed

succeeded
